# version: "3.8"

services:
  

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./api:/app
      - dotnet_cache:/root/.nuget/packages
    entrypoint: [ "dotnet", "watch", "run", "--urls", "http://*:80" ]
    # depends_on:
    #   - database
    environment:
      # Update connection string to use SQLite
      ConnectionStrings__MyPortfolio_v3_DB: "Data Source=/app/MyPortfolio.db"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    command: [ "npm", "run", "dev" ]
    depends_on:
      - backend
    networks:
      - app-network

  adminfrontend:
    build:
      context: ./adminfrontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./adminfrontend:/app
      - /app/node_modules
    ports:
      - "8081:3000"
    command: [ "npm", "run", "dev" ]
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  dotnet_cache:


networks:
  app-network:
    driver: bridge
